### ISSUE TITLE
Internal JS Error

### ISSUE THREAD

**Issue by kookma** [theSherwood/Mentat#17]
In https://admls.github.io/Mentat/ when you drag the floating widow to top edge
and its border crosses the top edge the red widow occurs with this error

Cannot read property of '0' of undefined

Strangely not all the time the error is appeared

**Comment by admls** [comment]
Is that happening on a touch screen or or when using the mouse? I think I'm getting something similar, but only when I'm using the mouse.

**Comment by kookma** [comment]
I encounter this issue when I use mouse!
By the way I am on a 17" touch monitor and so, I have both touch and mouse working on that

**Comment by admls** [comment]
I think this issue should be fixed now!

**Comment by kookma** [comment]
Yes, It is

Thank you

**Comment by kookma** [comment]
@admls 
A.
In experimenting with Volant when you try to drag one border (left or right) over other (means try to make the window width zero!) the JS red window appears! 

Strangely, I cannot reproduce it  always! but randomly I see the error

**Comment by admls** [comment]
I think this one is fixed now, too. Check it out if you get a minute and let me know!

Cheers!
