### ISSUE TITLE
Double click issue

### ISSUE THREAD

**Issue by kookma** [theSherwood/Mentat#19]
When you double clicked anything inside a window, a new tiddler is created with the below title:
$:/plugins/admls/volant-rapid/ui/rapid-menu-popup

Mohammad

**Comment by admls** [comment]
Good catch! There may still be some tiddlers from this possible future feature hanging around in the next release. But they shouldn't do anything.

**Comment by admls** [comment]
I've disabled the tiddlers causing the problem. They are still in the demo, but as of this latest release, they shouldn't do anything.

Best wishes,

Adam
