### ISSUE TITLE
Title bar issue: large number of open tiddlers

### ISSUE THREAD

**Issue by kookma** [theSherwood/Mentat#20]
When a lot number of tiddlers in a window, it seems the window title bar cannot handles them correctly! 
a. It seems title bar can show fixed number of titles
b. titles cannot be read, because when number of titles increases, the width start decreasing and you cannot read the titles! This may be okay, but one expects to be able to read the active title
c. I suggest to be able to scroll from left to right and vice versa!

Mohammad

**Comment by admls** [comment]
You're right. I'll experiment with scrolling.

**Comment by admls** [comment]
Are you saying that the tabs are currently flowing outside the window tiddler when there are too many? I'm unable to reproduce this error.

**Comment by kookma** [comment]
@admls 
No titles are not flowing outside window!
But when there is a lot of tiddlers open, some of titles are not visible in title bar!

--Mohammad

**Comment by admls** [comment]
Right. Okay. I'll see what I can do about scrolling window tabs. Cheers!

**Comment by admls** [comment]
@kookma 
Hi Mohammad,
The latest release has scrollable window tabs. For an added bonus, hold shift while scrolling over the window tabs to change the size of the tabs. There are one or two other options in the mentat config. 

Best wishes,

admls

**Comment by kookma** [comment]
Great!
Thank you admls.
